name: 🚀 Laravel Autopush
on:
  push:
    branches:
      - main  
jobs:
  FTP-Deploy-Action:
    name: 🎉 Correctly deployed
    runs-on: ubuntu-latest
    steps:
    - name: 📦 Getting changes
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: 📂 Sync repository files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: 21 # todo replace with your web hosts ftps port

        